use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ClientCommand {
    QueueJump,
    CycleMovementProfile,
    CycleDifficulty,
    CycleGameRulesPreset,
    ToggleRuleMobSpawning,
    ToggleRuleDaylightCycle,
    ToggleRuleWeatherCycle,
    ToggleRuleKeepInventory,
    ToggleSettingsMenu,
    SettingsMoveUp,
    SettingsMoveDown,
    SettingsApply,
    SetMoveLeft(bool),
    SetMoveRight(bool),
    ClearDirectionalInput,
    ToggleInventory,
    ToggleSneak,
    SetSneakHeld(bool),
    SelectHotbarSlot(u8),
    SetPrimaryAction(bool),
    SkipCompletionCredits,
    RespawnFromDeathScreen,
    SetJumpHeld(bool),
    TravelToOverworld,
    TravelToNether,
    TravelToEnd,
    TravelToSpawn,
    EquipDiamondLoadout,
    UseAt(i32, i32),
}
